export const Users = [
  {
    id: 1,
    name: "John Doe",
    age: 28,
    gender: "Male",
    email: "john.doe@example.com",
    country: "USA",
    isActive: true,
    company: "TechCorp",
    position: "Developer",
    joinDate: "2021-04-10",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 34,
    gender: "Female",
    email: "jane.smith@example.com",
    country: "Canada",
    isActive: false,
    company: "HealthPlus",
    position: "Nurse",
    joinDate: "2020-09-12",
  },
  {
    id: 3,
    name: "Sam Green",
    age: 40,
    gender: "Male",
    email: "sam.green@example.com",
    country: "Germany",
    isActive: true,
    company: "AutoWorld",
    position: "Mechanic",
    joinDate: "2019-11-20",
  },
  {
    id: 4,
    name: "Emily Brown",
    age: 26,
    gender: "Female",
    email: "emily.brown@example.com",
    country: "Japan",
    isActive: true,
    company: "FinTech",
    position: "Analyst",
    joinDate: "2022-01-15",
  },
  {
    id: 5,
    name: "Michael White",
    age: 45,
    gender: "Male",
    email: "michael.white@example.com",
    country: "USA",
    isActive: false,
    company: "TechCorp",
    position: "Manager",
    joinDate: "2017-07-30",
  },
  {
    id: 6,
    name: "Sophia Johnson",
    age: 38,
    gender: "Female",
    email: "sophia.johnson@example.com",
    country: "Canada",
    isActive: true,
    company: "GlobalMarket",
    position: "Sales Manager",
    joinDate: "2018-03-22",
  },
  {
    id: 7,
    name: "David Black",
    age: 32,
    gender: "Male",
    email: "david.black@example.com",
    country: "Germany",
    isActive: false,
    company: "AutoWorld",
    position: "Designer",
    joinDate: "2019-05-10",
  },
  {
    id: 8,
    name: "Linda Clark",
    age: 29,
    gender: "Female",
    email: "linda.clark@example.com",
    country: "Japan",
    isActive: true,
    company: "FinTech",
    position: "Project Manager",
    joinDate: "2020-08-05",
  },
  {
    id: 9,
    name: "Chris Davis",
    age: 41,
    gender: "Male",
    email: "chris.davis@example.com",
    country: "USA",
    isActive: true,
    company: "HealthPlus",
    position: "Doctor",
    joinDate: "2021-06-25",
  },
  {
    id: 10,
    name: "Patricia Miller",
    age: 37,
    gender: "Female",
    email: "patricia.miller@example.com",
    country: "Canada",
    isActive: false,
    company: "TechCorp",
    position: "HR Manager",
    joinDate: "2019-04-10",
  },
  {
    id: 11,
    name: "James Wilson",
    age: 33,
    gender: "Male",
    email: "james.wilson@example.com",
    country: "Germany",
    isActive: true,
    company: "AutoWorld",
    position: "Engineer",
    joinDate: "2018-12-15",
  },
  {
    id: 12,
    name: "Anna Harris",
    age: 22,
    gender: "Female",
    email: "anna.harris@example.com",
    country: "Japan",
    isActive: false,
    company: "GlobalMarket",
    position: "Intern",
    joinDate: "2022-05-01",
  },
  {
    id: 13,
    name: "Robert Martinez",
    age: 44,
    gender: "Male",
    email: "robert.martinez@example.com",
    country: "USA",
    isActive: true,
    company: "FinTech",
    position: "Director",
    joinDate: "2016-02-27",
  },
  {
    id: 14,
    name: "Laura Brown",
    age: 30,
    gender: "Female",
    email: "laura.brown@example.com",
    country: "Canada",
    isActive: true,
    company: "HealthPlus",
    position: "Pharmacist",
    joinDate: "2021-10-18",
  },
  {
    id: 15,
    name: "Kevin White",
    age: 39,
    gender: "Male",
    email: "kevin.white@example.com",
    country: "Germany",
    isActive: false,
    company: "TechCorp",
    position: "Support Engineer",
    joinDate: "2020-07-13",
  },
  {
    id: 16,
    name: "Nancy King",
    age: 36,
    gender: "Female",
    email: "nancy.king@example.com",
    country: "Japan",
    isActive: true,
    company: "FinTech",
    position: "Accountant",
    joinDate: "2021-03-25",
  },
  {
    id: 17,
    name: "Brian Green",
    age: 27,
    gender: "Male",
    email: "brian.green@example.com",
    country: "USA",
    isActive: true,
    company: "GlobalMarket",
    position: "Sales Executive",
    joinDate: "2019-09-16",
  },
  {
    id: 18,
    name: "Carol Carter",
    age: 42,
    gender: "Female",
    email: "carol.carter@example.com",
    country: "Canada",
    isActive: false,
    company: "HealthPlus",
    position: "Therapist",
    joinDate: "2020-01-20",
  },
  {
    id: 19,
    name: "Eric Hall",
    age: 31,
    gender: "Male",
    email: "eric.hall@example.com",
    country: "Germany",
    isActive: true,
    company: "AutoWorld",
    position: "Technician",
    joinDate: "2018-11-05",
  },
  {
    id: 20,
    name: "Betty Scott",
    age: 24,
    gender: "Female",
    email: "betty.scott@example.com",
    country: "Japan",
    isActive: true,
    company: "TechCorp",
    position: "Junior Developer",
    joinDate: "2022-06-30",
  },
  {
    id: 21,
    name: "Frank Nelson",
    age: 46,
    gender: "Male",
    email: "frank.nelson@example.com",
    country: "USA",
    isActive: false,
    company: "GlobalMarket",
    position: "Sales Director",
    joinDate: "2017-05-15",
  },
  {
    id: 22,
    name: "Helen Young",
    age: 35,
    gender: "Female",
    email: "helen.young@example.com",
    country: "Canada",
    isActive: true,
    company: "FinTech",
    position: "Financial Analyst",
    joinDate: "2019-07-22",
  },
  {
    id: 23,
    name: "Gary Collins",
    age: 29,
    gender: "Male",
    email: "gary.collins@example.com",
    country: "Germany",
    isActive: true,
    company: "AutoWorld",
    position: "Designer",
    joinDate: "2018-08-10",
  },
  {
    id: 24,
    name: "Ruth Roberts",
    age: 43,
    gender: "Female",
    email: "ruth.roberts@example.com",
    country: "Japan",
    isActive: false,
    company: "HealthPlus",
    position: "Head Nurse",
    joinDate: "2019-02-18",
  },
  {
    id: 25,
    name: "Edward Lewis",
    age: 37,
    gender: "Male",
    email: "edward.lewis@example.com",
    country: "USA",
    isActive: true,
    company: "TechCorp",
    position: "Software Architect",
    joinDate: "2017-12-01",
  },
  {
    id: 26,
    name: "Grace Turner",
    age: 33,
    gender: "Female",
    email: "grace.turner@example.com",
    country: "Canada",
    isActive: true,
    company: "FinTech",
    position: "Data Analyst",
    joinDate: "2020-09-10",
  },
];
